#!/usr/bin/env python3
"""
CSV Point Visualizer - Overlays points from CSV files generated by this locotrack repoonto original images

Usage:
    python csv_point_visualizer.py --csv path_to_csv --images path_to_images
    
Author: wyattPol
"""

import os
import argparse
import cv2
import pandas as pd

COLORS = {
    'A': (255, 0, 0),    
    'B': (0, 255, 0),    
    'C': (0, 0, 255),   
}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--csv', type=str, required=True)
    parser.add_argument('--images', type=str, required=True)
    parser.add_argument('--output', type=str, default='output_images')
    parser.add_argument('--width', type=int, default=768)
    parser.add_argument('--size', type=int, default=8)
    args = parser.parse_args()
    
    os.makedirs(args.output, exist_ok=True)
    df = pd.read_csv(args.csv)
    frames = sorted(df['frame'].unique())
    
    for frame in frames:
        image_file = f"{frame:06d}.png"
        image_path = os.path.join(args.images, image_file)
        
        if not os.path.exists(image_path):
            continue
        
        image = cv2.imread(image_path)
        if image is None:
            continue
            
        orig_height, orig_width = image.shape[:2]
        scale_x = orig_width / args.width
        
        frame_data = df[df['frame'] == frame]
        
        for cluster in ['A', 'B', 'C']:
            points = frame_data[frame_data['cluster'] == cluster]
            color = COLORS.get(cluster, (255, 255, 255))
            
            for _, p in points.iterrows():
                x = int(float(p['x']) * scale_x)
                y = int(float(p['y']) * scale_x)
                size = int(args.size * scale_x)
                
                cv2.circle(image, (x, y), size+2, (255, 255, 255), -1)
                cv2.circle(image, (x, y), size, color, -1)
        
        cv2.imwrite(os.path.join(args.output, f"frame_{frame}_points.png"), image)
    
    print(f"Done! Images saved to {args.output}")

if __name__ == "__main__":
    main() 
